"""
Train the mineral identification ensemble and calibrate its confidence.

    python scripts/train.py                    # default: config-driven
    python scripts/train.py --samples 250      # faster, slightly less accurate
    python scripts/train.py --rebuild-library  # re-ingest USGS data first

Pipeline
--------
1.  Build (or load) the spectral library: measured USGS splib07a entries plus
    physically synthesised MGM endmembers for anything not measured.
2.  Synthesise a large augmented training set on the *instrument's own
    wavelength grid*, so the model is trained on the exact evidence it will be
    asked to work from - not on 0.35-2.5 um library curves it will never see.
3.  Split three ways: train / calibrate / test. The calibration split is held
    out from training and used only to fit the temperature and the conformal
    threshold; the test split touches neither, so the reported coverage is an
    honest out-of-sample number.
4.  Fit the three-model ensemble.
5.  Fit temperature scaling and the conformal quantile on the calibration split.
6.  Evaluate on the test split and write metrics.json.

What the accuracy numbers mean
------------------------------
Test spectra are synthetic, generated by the same forward model that generated
the training data - so top-1 accuracy here measures how well the model inverts
that forward model under noise, mixing and grain-size variation. It is a real
and necessary measurement, but it is an upper bound on field performance,
because a real mineral is not exactly an MGM sum. Once you have measured known
standards on your own bench, add them under data/library/validation and they
become the authoritative test set. The honest number for field use is the
conformal coverage, which holds regardless of model quality.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend import config as cfg_mod                      # noqa: E402
from backend.library import store as libstore              # noqa: E402
from backend.models import calibration as calmod           # noqa: E402
from backend.models import classifier as clfmod            # noqa: E402


def main():
    ap = argparse.ArgumentParser(description="Train the spectral identification model")
    ap.add_argument("--samples", type=int, default=None,
                    help="training spectra per mineral (default from config)")
    ap.add_argument("--rebuild-library", action="store_true",
                    help="re-ingest the USGS library before training")
    ap.add_argument("--alpha", type=float, default=None,
                    help="conformal miscoverage rate (0.05 -> 95%% coverage)")
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--cache", action="store_true",
                    help="cache the synthesised dataset so repeat runs skip synthesis")
    args = ap.parse_args()

    cfg = cfg_mod.load_config()
    cfg_mod.ensure_dirs()

    n_per = args.samples or int(cfg.get_path("model.train.samples_per_class", 400))
    alpha = args.alpha if args.alpha is not None else float(
        cfg.get_path("model.conformal_alpha", 0.05))
    seed = args.seed or int(cfg.get_path("model.train.random_seed", 20260902))
    snr_range = tuple(cfg.get_path("model.train.noise_snr_range", [30, 400]))
    mix_frac = float(cfg.get_path("model.train.mixture_fraction", 0.45))

    grid = cfg_mod.analysis_grid()
    lo = float(cfg.get_path("instrument.wavelength_min_nm", 350.0))
    hi = float(cfg.get_path("instrument.wavelength_max_nm", 1000.0))
    wl = grid[(grid >= lo) & (grid <= hi)]

    print("=" * 74)
    print("  AI Spectroscopic Model - training")
    print("=" * 74)
    print(f"Instrument range : {wl.min():.0f} - {wl.max():.0f} nm  ({wl.size} channels)")

    t0 = time.time()
    print("\n[1/6] Spectral library")
    lib = libstore.get_library(rebuild=args.rebuild_library)
    summary = lib.summary()
    print(f"      {summary['n_entries']} spectra over {summary['n_classes']} minerals")
    print(f"      measured (USGS): {summary['sources']['usgs']}   "
          f"modelled: {summary['sources']['synthetic']}")
    if summary["sources"]["usgs"] == 0:
        print("      NOTE: no USGS spectra found. The model will train on modelled")
        print("            endmembers only. Run scripts/fetch_usgs_library.py to add")
        print("            measured references - it materially improves field accuracy.")

    print(f"\n[2/6] Synthesising training data ({n_per} per mineral)")

    def progress(done, total):
        pct = 100.0 * done / total
        sys.stdout.write(f"\r      {done}/{total}  ({pct:5.1f}%)")
        sys.stdout.flush()

    # Dataset synthesis is the slow part (minutes), and model tuning needs many
    # runs over identical data, so it is cached and keyed on everything that
    # affects it.
    from backend.processing import features as featmod
    cache_path = cfg.resolve("model.dir") / (
        f"dataset_v{featmod.FEATURE_VERSION}_n{n_per}_s{seed}_m{mix_frac}"
        f"_{int(wl.min())}-{int(wl.max())}_L{summary['n_entries']}.npz")
    if args.cache and cache_path.exists():
        print(f"      loading cached dataset {cache_path.name}")
        blob = np.load(cache_path, allow_pickle=True)
        ds = clfmod.Dataset(blob["X_spec"], blob["X_tab"], blob["y"],
                            list(blob["classes"]))
    else:
        ds = clfmod.build_dataset(lib, wl, samples_per_class=n_per,
                                  mixture_fraction=mix_frac, snr_range=snr_range,
                                  seed=seed, progress=progress)
        if args.cache:
            np.savez_compressed(cache_path, X_spec=ds.X_spec, X_tab=ds.X_tab,
                                y=ds.y, classes=np.array(ds.classes, dtype=object))
    print(f"\r      {ds.y.size} spectra, "
          f"{ds.X_spec.shape[1]} spectral + {ds.X_tab.shape[1]} tabular features")

    print("\n[3/6] Splitting train / calibrate / test (stratified 70/15/15)")
    rng = np.random.default_rng(seed + 1)
    tr_idx, cal_idx, te_idx = [], [], []
    for ci in np.unique(ds.y):
        idx = np.flatnonzero(ds.y == ci)
        rng.shuffle(idx)
        n = idx.size
        n_tr = int(round(0.70 * n))
        n_cal = int(round(0.15 * n))
        tr_idx.append(idx[:n_tr])
        cal_idx.append(idx[n_tr:n_tr + n_cal])
        te_idx.append(idx[n_tr + n_cal:])
    tr_idx = np.concatenate(tr_idx)
    cal_idx = np.concatenate(cal_idx)
    te_idx = np.concatenate(te_idx)
    print(f"      train {tr_idx.size} | calibrate {cal_idx.size} | test {te_idx.size}")

    print("\n[4/6] Fitting ensemble")
    clf = clfmod.EnsembleClassifier(ds.classes, wl)
    train_ds = clfmod.Dataset(ds.X_spec[tr_idx], ds.X_tab[tr_idx], ds.y[tr_idx], ds.classes)
    clf.fit(train_ds, log=lambda m: print(f"    {m}"))

    # Which minerals can this wavelength range actually diagnose? Used to report
    # the accuracy figure that describes real instrument capability alongside
    # the raw all-92-class number.
    from backend.models import matcher as matchmod
    probe = matchmod.SpectralMatcher(lib)
    diagnosable = {c for c in ds.classes
                   if probe.diagnostic_coverage(c, float(wl.min()), float(wl.max())) > 0.0}

    print("\n[5/6] Calibrating confidence")
    cal_probs = clf.predict_proba_batch(ds.X_spec[cal_idx], ds.X_tab[cal_idx])
    cal_y = ds.y[cal_idx]

    pre = calmod.evaluate(cal_probs, cal_y, ds.classes)
    bundle = calmod.CalibrationBundle()
    temp = bundle.scaler.fit(cal_probs, cal_y)
    cal_probs_scaled = bundle.scaler.transform(cal_probs)
    bundle.conformal = calmod.ConformalPredictor(alpha=alpha)
    qhat = bundle.conformal.fit(cal_probs_scaled, cal_y)
    post = calmod.evaluate(cal_probs_scaled, cal_y, ds.classes, bundle.conformal,
                           diagnosable)

    print(f"      temperature T = {temp:.3f}   conformal qhat = {qhat:.4f} "
          f"({bundle.conformal.method.upper()})")
    print(f"      ECE before {pre['expected_calibration_error']:.4f} "
          f"-> after {post['expected_calibration_error']:.4f}")

    print("\n[6/6] Evaluating on held-out test split")
    te_probs = bundle.scaler.transform(
        clf.predict_proba_batch(ds.X_spec[te_idx], ds.X_tab[te_idx]))
    test_metrics = calmod.evaluate(te_probs, ds.y[te_idx], ds.classes, bundle.conformal,
                                   diagnosable)

    print(f"      top-1 accuracy            : {test_metrics['top1_accuracy'] * 100:.2f}%")
    print(f"      top-3 accuracy            : {test_metrics['top3_accuracy'] * 100:.2f}%")
    print(f"      top-5 accuracy            : {test_metrics['top5_accuracy'] * 100:.2f}%")
    print(f"      expected calibration error: {test_metrics['expected_calibration_error']:.4f}")
    print(f"      conformal coverage        : "
          f"{test_metrics['conformal_empirical_coverage'] * 100:.2f}% "
          f"(target {test_metrics['conformal_target_coverage'] * 100:.0f}%)")
    print(f"      mean prediction-set size  : {test_metrics['conformal_mean_set_size']:.2f}")
    print(f"      singleton rate            : "
          f"{test_metrics['conformal_singleton_rate'] * 100:.1f}%")

    sub = test_metrics.get("diagnosable_subset")
    if sub:
        print(f"\n      Restricted to the {sub['n_minerals']} minerals this wavelength")
        print(f"      range can physically diagnose ({sub['n_test']} test spectra):")
        print(f"        top-1 accuracy          : {sub['top1_accuracy'] * 100:.2f}%")
        print(f"        top-3 accuracy          : {sub['top3_accuracy'] * 100:.2f}%")
        print(f"      The all-mineral figure above is dragged down by phases with no")
        print(f"      diagnostic feature in range - they cannot be separated by any")
        print(f"      method, because the information never reached the detector.")

    print("\n      hardest minerals for this instrument:")
    for name, acc in list(test_metrics["weakest_classes"].items())[:10]:
        print(f"        {acc * 100:5.1f}%  {name}")

    mdir = cfg.resolve("model.dir")
    mdir.mkdir(parents=True, exist_ok=True)
    clf.save(mdir / "ensemble.joblib")
    bundle.metrics = {"calibration": post}
    bundle.save(mdir / "calibration.npz")

    metrics = {
        "trained_at": time.time(),
        "elapsed_seconds": round(time.time() - t0, 1),
        "instrument_range_nm": [float(wl.min()), float(wl.max())],
        "samples_per_class": n_per,
        "feature_version": featmod.FEATURE_VERSION,
        "library": summary,
        "temperature": temp,
        "conformal_qhat": qhat,
        "conformal_method": bundle.conformal.method,
        "diagnosable_minerals": sorted(diagnosable),
        "calibration": post,
        "test": test_metrics,
    }
    (mdir / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")

    print(f"\nSaved to {mdir}")
    print(f"Total time {time.time() - t0:.1f}s")
    print("=" * 74)


if __name__ == "__main__":
    main()
